[map]
width = 500
height = 800
projection = "+init=epsg:3069" # This is the projection to use to draw the map
layers = ["Argentine.geojson", "lines.geojson", "points.geojson"]
output = "map.svg"
background = "rgba(45, 45, 244, 0.5)"
extent = "Argentine"
# extent = [-8214782.6791878305, -6086576.6304815235, -7384967.8868029471, -2408963.7082710671]

[Argentine]
fill = "red"
fill-opacity = "1"
stroke = "black"
stroke-width = "1.2"
stroke-opacity = "0.5"

[lines]
stroke = "green"
stroke-width = "2.6"

# Look! It use default values if I don't define any !
# [points]
# radius = "12"
# fill = "rgb(238, 79, 21)"

# OMG! I can set a title!
[title]
content = "OMG! Title!"
font-size = "38"
position = [400, 50]

[source]
content = "Source: xyz"
font-size = "20"
position = "right"

[graticule]
color = "grey"
