[map]
width = 500
height = 500
projection = "+init=epsg:3857"
layers = ["world.geojson", "afr.geojson"]
extent = [-10037508.342789244, 10037508.342789244, -10037508.342789244, 10037508.342789244]
output = "map2.svg"

[afr]
fill = "green"
fill-opacity = "1"
stroke = "black"
stroke-width = "0.7"
representation = "choropleth"

[world]
fill = "grey"
fill-opacity = "0.7"
stroke-width = "0.4"

[afr.choropleth]
field = "POP2005"
